language: node_js

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm ci

node_js:
  - "6"
  - "8"
  - "10"
  - "11"

env:
  - FORMDATA_VERSION=1.0.0
  - FORMDATA_VERSION=2.3.3

before_script:
  - 'if [ "$FORMDATA_VERSION" ]; then npm install form-data@^$FORMDATA_VERSION; fi'

before_install:
  - npm i -g npm@6.4.1

script: npm run report

cache:
  directories:
    - node_modules
